In [2]:
import numpy as np

In [4]:
#create a matrix

a = np.array([[1,2],[3,4]])

In [6]:
Ainv = np.linalg.inv(a)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
Ainv.dot(a)

array([[  1.00000000e+00,   0.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00]])

In [8]:
np.linalg.det(a)

-2.0000000000000004

In [9]:
np.diag(a)

array([1, 4])

In [10]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [12]:
a= np.array([2,3])
b= np.array([5,6])
np.outer(a,b)


array([[10, 12],
       [15, 18]])

In [13]:
np.inner(a,b)

28

In [14]:
np.diag(a).sum()

5

In [20]:
#  create guassian distribted data
X = np.random.randn(100, 3)
# X

cov = np.cov(X)
cov.shape   # wrong because it shud be 3X3

(100, 100)

In [23]:
cov = np.cov(X.T)
cov.shape
cov

array([[ 0.78224595,  0.0503666 ,  0.03200739],
       [ 0.0503666 ,  0.92207644, -0.08865993],
       [ 0.03200739, -0.08865993,  1.07957468]])

In [24]:
np.linalg.eigh(cov)

(array([ 0.75469736,  0.90956406,  1.11963567]),
 array([[ 0.9072302 ,  0.41979895,  0.02649902],
        [-0.37447513,  0.83476097, -0.40366137],
        [-0.19157697,  0.35629056,  0.91452463]]))

In [25]:
# Solving linear system
A = np.array([[1,2],[3,4]])
x = np.linalg.inv(A).dot(b)
x

array([-4. ,  4.5])

In [27]:
x = np.linalg.solve(A,b)
x

array([-4. ,  4.5])

In [31]:
A = np.array([[1,1],[1.5, 4]])
b = np.array([2200, 5050])
np.linalg.solve(A,b)

array([ 1500.,   700.])

In [7]:
x = np.array([[0.0],[3.5]])
w = np.array([[0.5, 0.1, -0.3],[0.7, -0.3, 0.2]])
b = np.array([[0.4], [0.1], [0]])



In [22]:
x1  = w.T.dot(x)
xm = x.dot(w)

ValueError: shapes (2,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [18]:
print w.T
print x1.shape

[[ 0.5  0.7]
 [ 0.1 -0.3]
 [-0.3  0.2]]
(3, 1)


In [16]:
x2 = x1+b

In [17]:
print x1

[[ 2.45]
 [-1.05]
 [ 0.7 ]]


In [19]:
print x2

[[ 2.85]
 [-0.95]
 [ 0.7 ]]


In [20]:
np.tanh(x2)

array([[ 0.99333039],
       [-0.73978305],
       [ 0.60436778]])